### ISSUE TITLE
Directly start verified SEB binary with prepared SEB config from SEB Verificator

### ISSUE THREAD

**Issue by TomJampen** [SafeExamBrowser/seb-win-verificator#1]
Hi

Instead of separating the two tasks (verifying SEB, starting the exam with prepared configuration) and leaving it to the teacher to "ensure" the actual **use** of the previously verified SEB binary (how could he/she know?), I propose to combine these tasks and embed the task of starting the exam directly into the SEB Verificator:

Preparation:
- let the teacher add the prepared SEB configuration file for the exam to the SEB Verificator

Start of the exam:
1. verify the SEB Browser with the SEB Verificator
2. automatically start the verified binary with the previously defined SEB configuration

Kind regards and thanks for your work
Tom

**Comment by dbuechel** [comment]
Thanks for your input, we'll definitely implement that use case. I hope we'll get around to doing it already for the official release, otherwise definitely for the next update version.

**Comment by dbuechel** [comment]
We have implemented the use case, so it definitely will be in the first official release. If you'd like, you can already test your use case with the latest development build: https://sebdev-let.ethz.ch/project/appveyor/seb-win-verificator/build/artifacts
